# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZUO-0w605llpsTOwIZphavdAl_pGCeBy
"""

###TITANIC DATASET
import pandas as pd
from sklearn.preprocessing import MinMaxScaler
df=pd.read_csv("train2.csv", sep=";", header=None)
df.columns = ['PassengerID', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']
print(df) 
### Extraction of gender basicly
# Extraction için gerekli sütunları seçme
df.to_csv('new_train.csv', index=False)
new_df= pd.read_csv("new_train.csv")
extraction_df = new_df[['Survived', 'Age', 'Sex', 'Fare']]
print("EXTRACTION:",extraction_df.head())
# Getting more basic and easy to classified Embarked column
new_df["EmbarkedC"] = (new_df["Embarked"] == "C").astype(int)
new_df["EmbarkedQ"] = (new_df["Embarked"] == "Q").astype(int)
new_df["EmbarkedS"] = (new_df["Embarked"] == "S").astype(int)
new_df['Sex'] = extraction_df['Sex'].replace({'male': 1, 'female': 0})
new_df.to_csv("train_feature_extracted.csv", index=False)
print(new_df)