# -*- coding: utf-8 -*-
"""20201704025.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_3OE3h0Dsp4T84K4Z_16x-r92deAnDD3
"""

import pandas as pd
from sklearn.preprocessing import MinMaxScaler
df=pd.read_csv("train2.csv", sep=";", header=None)
print(df) 
df.columns = ['PassengerID', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']
### Change the non-numeric values on "Fare" column to "NaN" and delete 
df["Fare"] = pd.to_numeric(df["Fare"], errors="coerce")
df.dropna(subset=["Fare"], inplace=True)
print(df["Fare"])
# Save new version
df.to_csv('newtitanic.csv', index=False)
#Finding and removing outliers
Q1 = df.quantile(0.25)
Q3 = df.quantile(0.75)
IQR = Q3 - Q1
outliers = df[((df < (Q1 - 1.5 * IQR)) |(df > (Q3 + 1.5 * IQR))).any(axis=1)]
print("OUTLIERS:\n", outliers)
# We dont need to clean outliers because there is no outlie