# -*- coding: utf-8 -*-
"""MIS220_SevvalOzyalcin.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uO70nB0dJ2iaxsSmZGoIoakj35g9z77S
"""

### EMBARKED column
import pandas as pd
df=pd.read_csv("train2.csv", sep=";", header=None)
print(df) 

df.columns = ['PassengerID', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']
df = df.iloc[1:]
#Removing rows which has missing values on embarked column
df.dropna(subset=['Embarked'], inplace=True)
print(df["Embarked"].isnull().sum())

##Save new version of csv
df.to_csv('new_train.csv', index=False)
new_df= pd.read_csv("new_train.csv")
print(new_df)

#checking again for missing values
missing_values = new_df.isnull().sum()
print(missing_values)