# -*- coding: utf-8 -*-
"""20201704090_101.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GAGGI01NgLVmqWOiE84TrO-Tix5NbOod
"""

import pandas as pd
from sklearn.preprocessing import MinMaxScaler
import matplotlib.pyplot as plt
df=pd.read_csv("train2 .csv", sep=";", header=None)
print(df) 
### Check for missing values
missing_values = df.isnull().sum()
print(missing_values)
# AGE column
# Mark as NaN non numeric values in AGE column
df.columns = ['PassengerID', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
# Creating of a new dataframe that includes values which are not NaN
age_data = df[df['Age'].notnull()]['Age']
#Average Mode and Median of AGE
average_age = age_data.mean()
age_data.plot(kind='hist', bins=20, title="Average of the Age Column")
plt.show()
mode_age = age_data.mode()
mode_age.plot(kind='hist', bins=20, title="Mode of the Age Column")
plt.show()
median_age= age_data.median()
median_data = age_data[age_data == median_age]
median_data.plot(kind='hist', bins=20, title="Median of the Age Column")
plt.show()
min_age = age_data.min()
max_age = age_data.max()
print("Average age:", average_age)
print("Median age:", median_age)
print("Mode age:", mode_age)
print("Minimum age:", min_age)
print("Maximum age:", max_age)
# Assigning NaN (Not a Number) instead of blank values in the age column
df["Age"].replace('', pd.np.nan, inplace=True)
# Filling missing values in age colum with average age value
df["Age"].fillna(average_age, inplace=True)
print(df['Age'].isnull().sum())
print("NEW AGE COLUMN:", df["Age"])